### PR TITLE
Update README with new Version information and change to cc-by-4.0 license

### PR DESCRIPTION
**Pull request by bannanc**
This PR adds the new version 1.0.8 to the README and updates the zenodo link to that DOI.

### CODE REVIEW

**Comment by bannanc** [comment]
I added the new license to address issue #88 and I double checked all the hyper links so I think issue #82 can be closed with this PR also

**Comment by bannanc** [comment]
@davidlmobley or @jchodera could you review and merge?

**Comment by bannanc** [comment]
@jchodera I know its cumbersome, but I also think its important to have the changes listed by release. There is a section at the bottom of the releases in the README for changes not in a current release that is typically updated with each PR and then a release is cut either when we've had a lot of changes or a bigish change (ie new chemical coverage or bug fixes). 

Since John approved this I'll go ahead and merge the changes.

**Comment by jchodera** [comment]
> @jchodera I know its cumbersome, but I also think its important to have the changes listed by release.

I totally agree that we need a changelog! I just wish there was a way to have the version that Zenodo mints a DOI for be the final version that already lists the changes in the current release!

**Comment by bannanc** [comment]
I guess you could do these three steps instead:

* Create a GitHub release 
    - where the readme has the new number with all changes to be included in the release without a link to the number
* Wait for Zenodo to mint a new DOI for the release
* Update the readme to include a link

I would be the same number of human steps, but at least mean the changelog in the versioned README has the changes in the right place even if it doesn't link to the DOI.

**Pull request merged**
