### PR TITLE
Convert to cookiecutter build system and add entry point mechanism for OpenFF toolkit

### PR DESCRIPTION
**Pull request by andrrizzi**
This converts the build system to use the cookiecutter way of doing things. I've also added the `entry_point` setting in `setup.py` to enable the mechanism proposed in openforcefield/openforcefield#117.

Right now, I've created a folder `smirnoff99Frosst/offxml/` that is supposed to include all the `offxml` files that will be installed with the package, but I'm happy to change the directory layout if you think we should do something else. I haven't touched the existing `smirnoff99Frosst/smirnoff99Frosst.offxml` file right now, but the idea is to move it into that folder.

### CODE REVIEW

**Comment by andrrizzi** [comment]
Thanks! Sounds like a good plan. I'll test locally whether the entry point system will work before merging and pushing on the conda package.

> You should move `smirnoff99Frosst.offxml` to `offxml/smirnoff99Frosst-1.0.8.offxml`

Will do.

**Comment by andrrizzi** [comment]
@j-wags actually, the file in this repo still uses the 0.1 SMIRNOFF spec. Should we update now?

**Comment by andrrizzi** [comment]
I'm also thinking of renaming the package from `smirnoff99Frosst` to `smirnoff99frosst` (all lowercase), if there are no objections.

**Comment by j-wags** [comment]
> actually, the file in this repo still uses the 0.1 SMIRNOFF spec. Should we update now?

Updating the spec will change the file version. That is, converting `smirnoff99Frosst-1.0.8.offxml` to the 0.2 spec creates `smirnoff99Frosst-1.1.8`. But yes, we should get a working FF in there for testing. 

Let's add [this file](https://github.com/openforcefield/openforcefield-forcefields/blob/master/forcefields/smirnoff99Frosst-1.1.8.offxml) to the repo, under the name `smirnoff99Frosst-1.1.8-prototype.offxml`. I had made it by hand and am reasonably certain that it's right, but we'll kick off lots of confusion if it's not, so we can keep `prototype` in the name until we "officially" check it.

**Comment by andrrizzi** [comment]
Based on our Slack conversation, we're going to release the toolkit version 0.3.0 before making a new `smirnoff99Frosst` release, so I think we can merge this for now, and pick it up later to add the updated offxml files.

**Pull request merged**
